// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monsters.Service.DAL;

namespace Monsters.Service.Migrations
{
    [DbContext(typeof(MonsterDbContext))]
    partial class MonsterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Monsters.DAL.Models.Door", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("KidBehindDoorName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("LastScare")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doors");

                    b.HasData(
                        new
                        {
                            Id = "door1",
                            KidBehindDoorName = "Rosie",
                            LastScare = new DateTime(2020, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Power = 30
                        },
                        new
                        {
                            Id = "door2",
                            KidBehindDoorName = "Abraham",
                            LastScare = new DateTime(2020, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Power = 50
                        },
                        new
                        {
                            Id = "door3",
                            KidBehindDoorName = "Moshe",
                            LastScare = new DateTime(2020, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Power = 60
                        },
                        new
                        {
                            Id = "door4",
                            KidBehindDoorName = "Danny",
                            LastScare = new DateTime(2020, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Power = 70
                        },
                        new
                        {
                            Id = "door5",
                            KidBehindDoorName = "Yoni",
                            LastScare = new DateTime(2020, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Power = 80
                        },
                        new
                        {
                            Id = "door6",
                            KidBehindDoorName = "Lev",
                            LastScare = new DateTime(2020, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Power = 90
                        },
                        new
                        {
                            Id = "door7",
                            KidBehindDoorName = "Maxim",
                            LastScare = new DateTime(2020, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Power = 1000
                        });
                });

            modelBuilder.Entity("Monsters.DAL.Models.Scare", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DoorId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MonsterId")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ScareBegin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScareEnded")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoorId");

                    b.ToTable("Scares");
                });

            modelBuilder.Entity("Monsters.DAL.Models.Scare", b =>
                {
                    b.HasOne("Monsters.DAL.Models.Door", "Door")
                        .WithMany()
                        .HasForeignKey("DoorId");
                });
#pragma warning restore 612, 618
        }
    }
}
